package cn.edu.zzia.career.dao.lt;

import java.util.List;
import java.util.Map;

import cn.edu.zzia.career.pojo.lt.Comment;


public interface CommentMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    int insert(Comment comment);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    List<Comment> selectList(Map<String, Object> query);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated
     */
    int update(Comment comment);
}